apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: juancifu31/hola-mundo-app:1.0
          ports:
            - containerPort: 80         
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            privileged: false

